import type { Theme } from '@/types';

const colors = {
  'activityBar.background': '#262626',
  'activityBar.border': '#ffffff10',
  'activityBarBadge.background': '#aa8866',
  'activityErrorBadge.background': '#be5046',
  'charts.red': '#be5046',
  'dropdown.background': '#1a1a1a',
  'dropdown.border': '#ffffff10',
  'editor.background': '#1a1a1a',
  'editor.findMatchBackground': '#ffffff10',
  'editor.findMatchHighlightBackground': '#ffffff20',
  'editor.findRangeHighlightBackground': '#ffffff30',
  'editor.foreground': '#b9b3ab',
  'editor.hoverHighlightBackground': '#ffffff40',
  'editor.lineHighlightBackground': '#ffffff08',
  'editor.rangeHighlightBackground': '#ffffff40',
  'editor.selectionBackground': '#ffffff20',
  'editor.selectionHighlightBackground': '#ffffff30',
  'editor.wordHighlightBackground': '#ffffff20',
  'editor.wordHighlightStrongBackground': '#ffffff40',
  'editorBracketMatch.background': '#ffffff10',
  'editorCursor.background': '#1a1a1a',
  'editorCursor.foreground': '#b9b3ab',
  'editorError.foreground': '#be5046',
  'editorGroupHeader.tabsBackground': '#262626',
  'editorGroupHeader.tabsBorder': '#ffffff10',
  'editorGutter.deletedBackground': '#be5046',
  'editorLineNumber.activeForeground': '#999999',
  'editorLineNumber.foreground': '#504b4b',
  'editorMarkerNavigationError.background': '#be5046',
  'editorMarkerNavigationError.headerBackground': '#be50461a',
  'editorOverviewRuler.deletedForeground': '#be504699',
  'editorRuler.foreground': '#d4be9830',
  focusBorder: '#504b4b',
  'gitDecoration.addedResourceForeground': '#81b88b',
  'gitlens.decorations.addedForegroundColor': '#81b88b',
  'input.background': '#1a1a1a',
  'input.border': '#ffffff10',
  'list.activeSelectionBackground': '#ffffff18',
  'list.errorForeground': '#c0777d',
  'list.hoverBackground': '#ffffff10',
  'list.inactiveSelectionBackground': '#ffffff10',
  'markdownAlert.caution.foreground': '#be5046',
  'minimapGutter.deletedBackground': '#be5046',
  'notificationsErrorIcon.foreground': '#be5046',
  'problemsErrorIcon.foreground': '#be5046',
  'scmGraph.historyItemHoverAdditionsForeground': '#81b88b',
  'sideBar.background': '#262626',
  'sideBar.border': '#ffffff10',
  'sideBarSectionHeader.background': '#262626',
  'sideBarSectionHeader.border': '#ffffff10',
  'statusBar.background': '#262626',
  'statusBar.border': '#ffffff10',
  'statusBar.debuggingBackground': '#cc663380',
  'statusBar.debuggingBorder': '#ff000000',
  'statusBar.debuggingForeground': '#ffffff',
  'statusBar.foreground': '#b9b3ab',
  'statusBar.noFolderBackground': '#996ddd',
  'statusBarItem.remoteBackground': '#5573afff',
  'statusBarItem.remoteForeground': '#f8fafd',
  'tab.activeBackground': '#1a1a1a',
  'tab.activeBorder': '#ffffff10',
  'tab.border': '#ffffff10',
  'tab.inactiveBackground': '#262626',
  'terminal.ansiBlack': '#3f4451',
  'terminal.ansiBlue': '#4aa5f0',
  'terminal.ansiBrightBlack': '#4f5666',
  'terminal.ansiBrightBlue': '#4dc4ff',
  'terminal.ansiBrightCyan': '#4cd1e0',
  'terminal.ansiBrightGreen': '#a5e075',
  'terminal.ansiBrightMagenta': '#de73ff',
  'terminal.ansiBrightRed': '#ff616e',
  'terminal.ansiBrightWhite': '#e6e6e6',
  'terminal.ansiBrightYellow': '#f0a45d',
  'terminal.ansiCyan': '#42b3c2',
  'terminal.ansiGreen': '#8cc265',
  'terminal.ansiMagenta': '#c162de',
  'terminal.ansiRed': '#e05561',
  'terminal.ansiWhite': '#d7dae0',
  'terminal.ansiYellow': '#d18f52',
  'terminal.background': '#1a1a1a',
  'terminal.border': '#3e4452',
  'terminal.foreground': '#abb2bf',
  'terminal.selectionBackground': '#abb2bf30',
  'terminalCommandDecoration.errorBackground': '#be5046',
  'testing.iconErrored': '#be5046',
  'testing.iconErrored.retired': '#be5046b3',
  'testing.iconFailed': '#be5046',
  'testing.iconFailed.retired': '#be5046b3',
  'testing.message.error.badgeBackground': '#be5046',
  'testing.message.error.badgeBorder': '#be5046',
  'testing.peekBorder': '#be5046',
  'testing.peekHeaderBackground': '#be50461a',
  'titleBar.activeBackground': '#323233',
  'titleBar.activeForeground': '#b9b3ab',
  'titleBar.inactiveBackground': '#3c3c3c',
  'titleBar.inactiveForeground': '#b9b3ab',
  'tree.indentGuidesStroke': '#ffffff10',
} satisfies Theme['colors'];

const tokenColorsReplacement = {
  gray: '#b9b3ab',
  lilac: '#c48fd4',
  rose: '#c0777d',
  yellow: '#ccaa88',
  teal: '#72b2bb',
  darkYellow: '#aa8866',
  lightBlue: '#80b4df',
  green: '#77aa88',
  white: '#ffff',
  darkGray: '#504b4b',
  midGray: '#948f89',
  red: '#ff6666',
  darkRed: '#be5046',
  purple: '#996ddd',
  blue: '#0000ff',
} satisfies Theme['tokenColorsReplacement'];

export default {
  name: 'Forest Dusk',
  type: 'dark',
  semanticHighlighting: true,
  colors,
  tokenColorsReplacement,
} satisfies Theme;
